singleServerConfig:
  address: "####"
  password: "######"  # Replace with the actual access key from Azure
  connectionPoolSize: 10
  connectionMinimumIdleSize: 2
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
